version: '3.4'
services:
  jira:
    image: cptactionhank/atlassian-jira:7.9.2
    restart: always
    links:
      - database
    volumes:
      - ~/var/jira-data:/var/atlassian/jira
      - ~/var/jira-logs:/opt/atlassian/jira/logs

  confluence:
    image: cptactionhank/atlassian-confluence:6.9.0
    restart: always
    links:
      - database
    volumes:
      - ~/var/confluence-data:/var/atlassian/confluence
      - ~/var/confluence-logs:/opt/atlassian/confluence/logs

  database:
    image: postgres:9.4
    restart: always
    volumes:
      - ./scripts/postgres-initdb.d:/docker-entrypoint-initdb.d
      - ~/var/database-data:/var/lib/postgresql/data
  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
    links:
      - jira
      - confluence
    volumes:
    - ./:/src
    command: ./src/scripts/run_nginx.sh
    environment:
    - DOMAIN
volumes:
  jira-data:
  confluence-data:
  database-data:
