version: '3.4'
services:
  jira:
    image: cptactionhank/atlassian-jira:7.9.2
    restart: always
    links:
      - database
    volumes:
      - jira-data:/var/atlassian/jira

  confluence:
    image: cptactionhank/atlassian-confluence:6.9.0
    restart: always
    links:
      - database
    volumes:
      - confluence-data:/var/atlassian/confluence

  database:
    image: postgres:9.4
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data
  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
    links:
      - jira
      - confluence
    volumes:
    - ./:/src
    command: ./src/scripts/run_nginx.sh
    environment:
    - DOMAIN
volumes:
  jira-data:
  confluence-data:
  database-data:
